language: cpp
compiler:
  - gcc
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
install:
  - sudo apt-get install -qq libboost-test-dev libboost-iostreams-dev
script:
  - make test
